stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: mvn -Dmaven.test.failure.ignore=true clean
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: yahya/simpleservice
      registry: 127.0.0.1:34095
timeout: 60
