stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: mvn -Dmaven.test.failure.ignore=true test
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: yahyaozturk/simpleservice:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
timeout: 60
