stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: mvn -Dmaven.test.failure.ignore=true test
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: yahyaozturk/simpleservice:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34988
- name: Deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
timeout: 60
