stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: mvn -Dmaven.test.failure.ignore=true test
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: yahya/simpleservice
      registry: registry.hub.docker.com
timeout: 60
