kind: Service
apiVersion: v1
metadata:
  name: simple-service
spec:
  selector:
    app: simpleservice
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-simpleservice
  labels:
    app: simpleservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleservice
  template:
    metadata:
      labels:
        app: simpleservice
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: simpleservice
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80